### ISSUE TITLE
Add card number generation function 

### ISSUE THREAD

**Issue by SaronTetra** [SaronTetra/WattOhm#16]
Cards use Luhn algorithm
Make sure to also add unit tests

**Comment by SaronTetra** [comment]
Generation and validation

**Comment by SzymCrusader** [comment]
The first 6 digits of a credit card number are known as the Issuer Identification Number (IIN)

**Comment by SzymCrusader** [comment]
Visa: Card numbers start with a 4.
MasterCard: Card numbers start with the numbers 51 through 55.

**Comment by SzymCrusader** [comment]
532315 - WattOhm IIN
Can be changed later
